proseWrap: preserve
printWidth: 120
tabWidth: 2
useTabs: false
endOfLine: lf
embeddedLanguageFormatting: off
plugins:
  - prettier-plugin-compact-markdown-table
  - prettier-plugin-zhfmt
tableLayout: compact
overrides:
  - files: "**/*.md"
    options:
      tabWidth: 4
